// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApHFvfDV4-5bD6mgbG7myVsw4G2CjBd9I',
    appId: '1:333963577921:web:3e5e218dcb82092d8214c0',
    messagingSenderId: '333963577921',
    projectId: 'exam-6e4c2',
    authDomain: 'exam-6e4c2.firebaseapp.com',
    storageBucket: 'exam-6e4c2.appspot.com',
    measurementId: 'G-3EVW4VDD44',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPOj58lM-Bhig1qsLdvyBv6oArw0DgYrE',
    appId: '1:333963577921:android:a9f0c068196ecd1b8214c0',
    messagingSenderId: '333963577921',
    projectId: 'exam-6e4c2',
    storageBucket: 'exam-6e4c2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0-dliIzSvGDGclsLwNoySy4rJ296_1Jo',
    appId: '1:333963577921:ios:2ab07c39067c17158214c0',
    messagingSenderId: '333963577921',
    projectId: 'exam-6e4c2',
    storageBucket: 'exam-6e4c2.appspot.com',
    iosClientId: '333963577921-is85hbint410ie43nvjfnncuc34p9ftl.apps.googleusercontent.com',
    iosBundleId: 'com.myorder.exam.exam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0-dliIzSvGDGclsLwNoySy4rJ296_1Jo',
    appId: '1:333963577921:ios:744ea3c6b3ffb05c8214c0',
    messagingSenderId: '333963577921',
    projectId: 'exam-6e4c2',
    storageBucket: 'exam-6e4c2.appspot.com',
    iosClientId: '333963577921-4le3v5gcpfv42k1jc0rh2917f9dnpuf1.apps.googleusercontent.com',
    iosBundleId: 'com.myorder.exam.exam.RunnerTests',
  );
}
